- name: Install Nginx
  hosts: localhost
  become: yes
  tasks:
  - name: install nginx latest version
    ansible.builtin.dnf:
      name: 
      - mysql
      state: absent
  - name: install nginx latest version
    ansible.builtin.dnf:
      name: 
      - java-11-openjdk-devel
      state: latest
  - name: start nginx service
    ansible.builtin.service:
      name: nginx
      state: started    