- name: print variable from Prompt
  hosts: localhost
  vars_prompt:
  - name : USERNAME
    prompt: Please enter your username
    private: false
  tasks:
  - name: print variable from prompt
    ansible.builtin.debug:
      msg: "Your Entered Username is {{USERNAME}}"


